@echo off
TITLE Potatochip
echo Updating Potatochip...
git pull
echo Updating dependencies...
start cmd /c npm install
echo Migrating database...
start cmd /c npx prisma migrate dev --name autoupdate
@echo on
timeout /t 10
echo Starting PotatoChip...
node main.js