@echo off
TITLE Potatochip
echo Updating Potatochip...
git pull
echo Updating dependencies...
start /B /WAIT cmd /c npm install
echo Migrating database...
start /B /WAIT cmd /c npx prisma migrate dev --name autoupdate
@echo on
echo Starting PotatoChip...
node main.js